In [1]:
import cv2   # cv = computer vision
import numpy as np  # numerical python

In [2]:
# 1. READING THE IMAGE
# Replace 'path_to_image.jpg' with an actual image file on your computer
img = cv2.imread("images/birds.jpg")

In [3]:
# Check if image loaded correctly
if img is None:
    print("Error: Could not find image.")
    exit()

In [8]:
cv2.imwrite("tests/img.jpg", img=img)

True

In [4]:
img

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 252],
        [255, 255, 255],
        [254, 254, 254]],

       [[246, 255, 249],
        [244, 255, 249],
        [246, 255, 249],
        ...,
        [248, 255, 249],
        [248, 255, 251],
        [248, 255, 251]],

       [[ 47,  89,  58],
        [ 45,  89,  58],
        [ 47,  89,  58],
        ...,
        [ 59,  91,  66],
        [ 64,  93,  70],
        [ 65,  93,  73]],

       ...,

       [[ 11,  61,  57],
        [ 11,  61,  57],
        [ 11,  61,  57],
        ...,
        [ 45,  88, 103],
        [ 47,  88, 103],
        [ 49,  88, 102]],

       [[ 27,  59,  58],
        [ 27,  59,  58],
        [ 27,  59,  58],
        ...,
        [ 60,  88,  99],
        [ 62,  88, 100],
        [ 62,  89,  99]],

       [[234, 255, 255],
        [234, 255, 255],
        [234, 255, 255],
        ...,
        [232, 255, 255],
        [236, 255, 255],
        [236, 255, 255]]

In [5]:
img[:,:, 0]

array([[255, 255, 255, ..., 255, 255, 254],
       [246, 244, 246, ..., 248, 248, 248],
       [ 47,  45,  47, ...,  59,  64,  65],
       ...,
       [ 11,  11,  11, ...,  45,  47,  49],
       [ 27,  27,  27, ...,  60,  62,  62],
       [234, 234, 234, ..., 232, 236, 236]], shape=(396, 726), dtype=uint8)

In [ ]:
R
B 
G

In [6]:
img[:, :, 1]

array([[255, 255, 255, ..., 255, 255, 254],
       [255, 255, 255, ..., 255, 255, 255],
       [ 89,  89,  89, ...,  91,  93,  93],
       ...,
       [ 61,  61,  61, ...,  88,  88,  88],
       [ 59,  59,  59, ...,  88,  88,  89],
       [255, 255, 255, ..., 255, 255, 255]], shape=(396, 726), dtype=uint8)

In [7]:
img[:, :, 2]

array([[255, 255, 255, ..., 252, 255, 254],
       [249, 249, 249, ..., 249, 251, 251],
       [ 58,  58,  58, ...,  66,  70,  73],
       ...,
       [ 57,  57,  57, ..., 103, 103, 102],
       [ 58,  58,  58, ...,  99, 100,  99],
       [255, 255, 255, ..., 255, 255, 255]], shape=(396, 726), dtype=uint8)

In [6]:
# image is 2d array and 3 layers for BGR format

In [7]:
img[:, :, 1]

array([[255, 255, 255, ..., 255, 255, 254],
       [255, 255, 255, ..., 255, 255, 255],
       [ 89,  89,  89, ...,  91,  93,  93],
       ...,
       [ 61,  61,  61, ...,  88,  88,  88],
       [ 59,  59,  59, ...,  88,  88,  89],
       [255, 255, 255, ..., 255, 255, 255]], shape=(396, 726), dtype=uint8)

In [9]:
# 2. CONVERTING COLOR
# OpenCV reads in BGR. Most processing is easier in Grayscale (0-255 intensity)
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

In [10]:
img_gray

array([[255, 255, 255, ..., 254, 255, 254],
       [252, 252, 252, ..., 252, 253, 253],
       [ 75,  75,  75, ...,  80,  83,  84],
       ...,
       [ 54,  54,  54, ...,  88,  88,  88],
       [ 55,  55,  55, ...,  88,  89,  89],
       [253, 253, 253, ..., 252, 253, 253]], shape=(396, 726), dtype=uint8)

In [11]:
# write to an image
cv2.imwrite("tests/output.jpg", img_gray)

True

In [13]:
img

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 252],
        [255, 255, 255],
        [254, 254, 254]],

       [[246, 255, 249],
        [244, 255, 249],
        [246, 255, 249],
        ...,
        [248, 255, 249],
        [248, 255, 251],
        [248, 255, 251]],

       [[ 47,  89,  58],
        [ 45,  89,  58],
        [ 47,  89,  58],
        ...,
        [ 59,  91,  66],
        [ 64,  93,  70],
        [ 65,  93,  73]],

       ...,

       [[ 11,  61,  57],
        [ 11,  61,  57],
        [ 11,  61,  57],
        ...,
        [ 45,  88, 103],
        [ 47,  88, 103],
        [ 49,  88, 102]],

       [[ 27,  59,  58],
        [ 27,  59,  58],
        [ 27,  59,  58],
        ...,
        [ 60,  88,  99],
        [ 62,  88, 100],
        [ 62,  89,  99]],

       [[234, 255, 255],
        [234, 255, 255],
        [234, 255, 255],
        ...,
        [232, 255, 255],
        [236, 255, 255],
        [236, 255, 255]]

In [12]:
# splitting channels

b, g, r = cv2.split(img)

In [14]:
b

array([[255, 255, 255, ..., 255, 255, 254],
       [246, 244, 246, ..., 248, 248, 248],
       [ 47,  45,  47, ...,  59,  64,  65],
       ...,
       [ 11,  11,  11, ...,  45,  47,  49],
       [ 27,  27,  27, ...,  60,  62,  62],
       [234, 234, 234, ..., 232, 236, 236]], shape=(396, 726), dtype=uint8)

In [15]:
img[:, :, 0]

array([[255, 255, 255, ..., 255, 255, 254],
       [246, 244, 246, ..., 248, 248, 248],
       [ 47,  45,  47, ...,  59,  64,  65],
       ...,
       [ 11,  11,  11, ...,  45,  47,  49],
       [ 27,  27,  27, ...,  60,  62,  62],
       [234, 234, 234, ..., 232, 236, 236]], shape=(396, 726), dtype=uint8)

In [16]:
cv2.imwrite("tests/output_channel_b.jpg", b)

True

In [17]:
cv2.imwrite("tests/output_channel_r.jpg", r)

True

In [18]:
cv2.imwrite("tests/output_channel_g.jpg", g)

True

In [19]:
cv2.imwrite("tests/merged.jpg", cv2.merge([b, g, r]))

True

In [20]:
b_gray, g_gray, r_gray = cv2.split(img_gray)

ValueError: not enough values to unpack (expected 3, got 1)

In [ ]:
# 3. GEOMETRY (Resize and Flip)
# Resize to a specific width and height (500x500)

In [17]:
img

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 252],
        [255, 255, 255],
        [254, 254, 254]],

       [[246, 255, 249],
        [244, 255, 249],
        [246, 255, 249],
        ...,
        [248, 255, 249],
        [248, 255, 251],
        [248, 255, 251]],

       [[ 47,  89,  58],
        [ 45,  89,  58],
        [ 47,  89,  58],
        ...,
        [ 59,  91,  66],
        [ 64,  93,  70],
        [ 65,  93,  73]],

       ...,

       [[ 11,  61,  57],
        [ 11,  61,  57],
        [ 11,  61,  57],
        ...,
        [ 45,  88, 103],
        [ 47,  88, 103],
        [ 49,  88, 102]],

       [[ 27,  59,  58],
        [ 27,  59,  58],
        [ 27,  59,  58],
        ...,
        [ 60,  88,  99],
        [ 62,  88, 100],
        [ 62,  89,  99]],

       [[234, 255, 255],
        [234, 255, 255],
        [234, 255, 255],
        ...,
        [232, 255, 255],
        [236, 255, 255],
        [236, 255, 255]]

In [21]:
cv2.resize(img, (500, 500))
# this increase grid

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [254, 255, 251],
        [255, 255, 253],
        [254, 254, 254]],

       [[248, 255, 251],
        [248, 255, 251],
        [248, 255, 251],
        ...,
        [248, 255, 247],
        [250, 255, 250],
        [250, 255, 252]],

       [[150, 175, 157],
        [150, 175, 157],
        [149, 175, 157],
        ...,
        [155, 175, 157],
        [158, 176, 162],
        [160, 177, 165]],

       ...,

       [[ 19,  60,  57],
        [ 19,  60,  57],
        [ 19,  60,  57],
        ...,
        [ 50,  88, 100],
        [ 53,  88, 101],
        [ 55,  88, 101]],

       [[ 92, 120, 119],
        [ 92, 120, 119],
        [ 92, 120, 119],
        ...,
        [111, 140, 148],
        [114, 140, 148],
        [116, 141, 148]],

       [[234, 255, 255],
        [234, 255, 255],
        [234, 255, 255],
        ...,
        [231, 255, 255],
        [233, 255, 255],
        [236, 255, 255]]

In [23]:
cv2.imwrite("tests/resized_img.jpg", cv2.resize(img, (500, 500)))

True

In [25]:
cv2.imwrite("tests/resized_img1.jpg", cv2.resize(img, (500, 100)))

True

In [27]:
img_resized = cv2.resize(img, (500, 500))

In [28]:
# Flip the image: 1 = horizontal, 0 = vertical, -1 = both
img_flipped_horizontal = cv2.flip(img_resized, 1)
cv2.imwrite("tests/flipped_horizontal.jpg", img_flipped_horizontal)

True

In [30]:
cv2.imwrite("tests/stacked.jpg",np.hstack((img_resized, img_flipped_horizontal)))

True

In [31]:
img_flipped_vertical = cv2.flip(img_resized, 0)
cv2.imwrite("tests/flipped_vertical.jpg", img_flipped_vertical)

True

In [32]:
cv2.imwrite("tests/stacked_vertical.jpg", np.hstack((img_resized, img_flipped_vertical)))

True

In [33]:
img_flipped_both = cv2.flip(img_resized, -1)
cv2.imwrite("tests/flipped_both.jpg", img_flipped_both)

True

In [35]:
cv2.imwrite("tests/stacked_both.jpg", np.hstack((img_resized, img_flipped_both)))

True

In [25]:
# 4. DRAWING ON THE IMAGE
# Format: (image, coordinates, color_BGR, thickness)
# Note: (0,0) is the top-left corner of the image



In [26]:
img_flipped_horizontal

array([[[254, 254, 254],
        [255, 255, 253],
        [254, 255, 251],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[250, 255, 252],
        [250, 255, 250],
        [248, 255, 247],
        ...,
        [248, 255, 251],
        [248, 255, 251],
        [248, 255, 251]],

       [[160, 177, 165],
        [158, 176, 162],
        [155, 175, 157],
        ...,
        [149, 175, 157],
        [150, 175, 157],
        [150, 175, 157]],

       ...,

       [[ 55,  88, 101],
        [ 53,  88, 101],
        [ 50,  88, 100],
        ...,
        [ 19,  60,  57],
        [ 19,  60,  57],
        [ 19,  60,  57]],

       [[116, 141, 148],
        [114, 140, 148],
        [111, 140, 148],
        ...,
        [ 92, 120, 119],
        [ 92, 120, 119],
        [ 92, 120, 119]],

       [[236, 255, 255],
        [233, 255, 255],
        [231, 255, 255],
        ...,
        [234, 255, 255],
        [234, 255, 255],
        [234, 255, 255]]

In [27]:
# Draw a Green Line (BGR: 0, 255, 0)
cv2.line(img_flipped_horizontal, (0, 0), (200, 200), (0, 255, 0), 5)

array([[[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [248, 255, 251],
        [248, 255, 251],
        [248, 255, 251]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [149, 175, 157],
        [150, 175, 157],
        [150, 175, 157]],

       ...,

       [[ 55,  88, 101],
        [ 53,  88, 101],
        [ 50,  88, 100],
        ...,
        [ 19,  60,  57],
        [ 19,  60,  57],
        [ 19,  60,  57]],

       [[116, 141, 148],
        [114, 140, 148],
        [111, 140, 148],
        ...,
        [ 92, 120, 119],
        [ 92, 120, 119],
        [ 92, 120, 119]],

       [[236, 255, 255],
        [233, 255, 255],
        [231, 255, 255],
        ...,
        [234, 255, 255],
        [234, 255, 255],
        [234, 255, 255]]

In [39]:

cv2.imwrite("tests/line.jpg", cv2.line(img_flipped_horizontal, (0, 0), (200, 200), (255, 50, 0), 5))

True

In [40]:

# Draw a Red Rectangle (Top-Left, Bottom-Right)
cv2.imwrite("tests/rectangle.jpg", cv2.rectangle(img_flipped_horizontal, (300, 50), (450, 150), (0, 0, 255), 3))

True

In [ ]:

# Draw a Blue Filled Circle (Center, Radius)
# Using -1 for thickness fills the shape
cv2.imwrite("tests/circle.jpg", cv2.circle(img_flipped_horizontal, (100, 400), 50, (255, 0, 0), -1))

True

In [43]:

# Add White Text
cv2.imwrite("tests/white_text.jpg", cv2.putText(img_flipped_horizontal, "OpenCV Lesson 1", (150, 480), 
            cv2.FONT_HERSHEY_COMPLEX, 1, (255, 255, 255), 2))

True

In [44]:

# 5. STACKING AND DISPLAYING
# To show images side-by-side, they must have the same number of channels.
# Since img_gray has 1 channel, we convert it back to 3 channels to stack with RGB.
gray_3_channel = cv2.cvtColor(img_gray, cv2.COLOR_GRAY2BGR)
gray_resized = cv2.resize(gray_3_channel, (500, 500))

In [45]:
# Horizontal stack: Original (resized) next to the Edited version
hor_stack = np.hstack((gray_resized, img_flipped_horizontal))

In [46]:
cv2.imshow("Left: Gray | Right: Edited & Flipped", hor_stack)

In [47]:
cv2.imwrite("tests/stacked.jpg", np.hstack((gray_resized, img_flipped_horizontal)))

True

In [38]:
cv2.imwrite("tests/vstacked.jpg", np.vstack((gray_resized, img_flipped_horizontal)))

True

In [ ]:
# # Wait for any key press to close the windows
# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [ ]:








# 6. SAVING AND CLOSING
cv2.imwrite("my_first_output.jpg", img_flipped)

# Wait for any key press to close the windows
cv2.waitKey(0)
cv2.destroyAllWindows()

NameError: name 'img_flipped' is not defined